sudo: required
services:
  - docker


before_install:
  - docker build -t vilastadoori/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vilastadoori/docker-react npm run test

  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "vilas-aws-docker-test"
    env: "Vilas-aws-docker-test-env"
    bucket_name: "elasticbeanstalk-us-east-2-105366316698"
    bucket_path: "vilas-aws-docker-test"
    on:
      branch: feature
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"